### ISSUE TITLE
[Bug] App crashes on opening Downloads menu

### ISSUE THREAD

**Issue by bachig26** [insomniachi/Totoro#1]
I'm using the latest build 0.4.1. I was browsing around the app to get familiarize with the options.

And when try to open the Downloads menu (Sidebar), the app crashes.
This crash is persistent and I haven't used much with previous version, I don't know if this is a long present bug.

System Information:
OS: Windows 10 (21H1)

**Comment by insomniachi** [comment]
I looked at the code and couldn't find a reason it could crash.
can you once again make the app crash and go to Event Viewer (it's an in-built app in windows)
![image](https://user-images.githubusercontent.com/6525704/208823408-3254e1d3-e29e-407d-9443-49ccc9529395.png)
Windows Logs -> Application -> There would be two errors, can you give me screenshots of both ?

**Comment by bachig26** [comment]
> I looked at the code and couldn't find a reason it could crash.
> 
> can you once again make the app crash and go to Event Viewer (it's an in-built app in windows)
> 
> ![image](https://user-images.githubusercontent.com/6525704/208823408-3254e1d3-e29e-407d-9443-49ccc9529395.png)
> 
> Windows Logs -> Application -> There would be two errors, can you give me screenshots of both ?

sure I'll do as soon as possible 👍

**Comment by insomniachi** [comment]
download uses https://www.shanaproject.com/ to download torrents, i have not tested it that much.
