### ISSUE TITLE
site request : kamyroll

### ISSUE THREAD

**Issue by venkat2305** [insomniachi/Totoro#10]
add kamyroll. https://github.com/kamyroll
it scrapes from crunchyroll and it would be a great addition

**Comment by bachig26** [comment]
@insomniachi i would suggest add Crunchyroll from consumet api.

https://github.com/consumet/consumet.ts/blob/master/src/providers/anime/crunchyroll.ts

https://github.com/consumet/api.consumet.org/blob/main/src/routes/anime/crunchyroll.ts

**Comment by venkat2305** [comment]
Does consumet api has any advantage?

**Comment by bachig26** [comment]
> Does consumet api has any advantage? 

Kamyroll is hosted using US server, so the content is restricted to we can watch on US, if some content is exclusive for other location then you can't see vice versa.

In case of Consumet API, they host their API in US, Europe, some country in Asia. so, if watch from Europe you can experience the contents that's available in that part and if you use VPN with US server, you can watch US content that's exclusive there, which is highly useful in many ways.

**Comment by venkat2305** [comment]
That's not true. I can see many anime that were blocked in my region in crunchyroll using kamyroll.

**Comment by insomniachi** [comment]
Looks like consumet api was using kamyroll before as crunchyroll, now they have something new, idk if it's still using kamyroll under the hood.

Kamyroll takes location as argument, so it should be able to get everything.

**Comment by bachig26** [comment]
> Looks like consumet api was using kamyroll before as crunchyroll, now they have something new, idk if it's still using kamyroll under the hood.

Yes, they used Kamyroll as Crunchyroll. After developing their own API for crunchyroll called cronchy, now they have both. 


> Kamyroll takes location as argument, so it should be able to get everything.

I don't know about it. But I have asked this question to the Kamyroll and Consumet developers last month and they gave this answer.

**Comment by insomniachi** [comment]
Added Kamyroll.
Also added Consumet, but can only use Zoro and animepahe from it at the moment. (It doesn't seem to play audio from animepahe)

![image](https://user-images.githubusercontent.com/6525704/213910681-f69c1602-a2b4-4d2f-9be5-99c57902df55.png)
now valid values are only zoro/animepahe but more will be added

you get this dialog by clicking the defaultprovider in settings.

**Comment by venkat2305** [comment]
Hey, @insomniachi kamyroll just got a DMCA. Could you please add crunchyroll from consumet api?

**Comment by insomniachi** [comment]
it's already there.
![image](https://user-images.githubusercontent.com/6525704/214773460-24adaa1c-ad97-4b29-894f-5c1c374a82ef.png)
change the provider to `crunchyroll`

**Comment by venkat2305** [comment]
search isn't working. and there's a weird dialog before opening the player. What is it? 

https://user-images.githubusercontent.com/55329452/214787649-f9af623a-f838-4515-8d13-e4d3eb91373b.mp4

**Comment by insomniachi** [comment]
can you give me log files in AppData\Local\Totoro\ApplicationData\Logs.
The dialog is, in order to gat Mal Id, i need it to search the opening/ed skip information. also to update anilist/mal to tracking.
if it cannot resolve it from title, it asks you to select select from the list.

but something is wrong here, i'll check.

**Comment by venkat2305** [comment]
For some anime it is showing a list of anime for some it's empty.

**Comment by venkat2305** [comment]
@insomniachi please add English subs for kamyroll Japanese dub.

**Comment by insomniachi** [comment]
> it's already there. ![image](https://user-images.githubusercontent.com/6525704/214773460-24adaa1c-ad97-4b29-894f-5c1c374a82ef.png) change the provider to `crunchyroll`

for now, you can do.
Change CrunchyrollStreamType to 'dub'. but then it'll only show dubs.

but i'll update it later to show both.

**Comment by venkat2305** [comment]
Crunchyroll has dubs for many languages. Also, it would be great to have an option to select sub or dub on the player itself

**Comment by venkat2305** [comment]
there are no subtitles. Please add it.

**Comment by insomniachi** [comment]
You mean for dubs ?
i have no idea on how to load external subtitles right now. will add if i ever figure out how to.

**Comment by venkat2305** [comment]
For Japanese dub. There are no hard subs and there are no soft subs

**Comment by insomniachi** [comment]
can you tell which show and episode? so i can check what the api returns.

**Comment by venkat2305** [comment]
Demon slayer season 1 episode 1

**Comment by insomniachi** [comment]
added, closing this.
![image](https://user-images.githubusercontent.com/6525704/215256424-d8462cad-3222-4a34-9635-f46efbf11b6f.png)

**Comment by venkat2305** [comment]
Can I post all the bugs related to crunchyroll here?

1. Can you try to play " the Angel next door spoils me rotten" and "Vinland saga season 2" in  crunchyroll. I think there's an issue with the current season anime. I can't play them but it works fine with completed anime.

2. Recently aired page is empty for crunchyroll. Can you look into this?

**Comment by insomniachi** [comment]
i'm moving it to new issue.
