### ISSUE TITLE
please check this bug

### ISSUE THREAD

**Issue by venkat2305** [insomniachi/Totoro#11]
https://user-images.githubusercontent.com/55329452/213905795-b1cbf1bb-6e81-46da-b991-349756e8b7c8.mp4

**Comment by insomniachi** [comment]
which anime/episode did you click ?
is the still present in current version ?

**Comment by venkat2305** [comment]
provider is all anime and check this video for the anime name. it happens with all the anime. also, there are so many crashes. searching for an anime in the search tab crashes the app. changing the source crashes the app. the app seems pretty unstable.

https://user-images.githubusercontent.com/55329452/213923438-9a26f71b-53ff-4086-ac19-15e20dfe04ef.mp4

at the end of this video , the app crashed

**Comment by insomniachi** [comment]
crash in the video is fixed.

i'm not sure what the rest means. doesn't crash for me.
`searching for an anime in the search tab crashes the app`
`changing the source crashes the app`

Some known issues.
AnimePahe cannot be used, it will be removed.
App might crash when provider is not responding.

there will be a log file generated on \AppData\Local\Totoro\ApplicationData\Logs
that will be helpful in case of crashes.
