### ISSUE TITLE
separate tab for player

### ISSUE THREAD

**Issue by venkat2305** [insomniachi/Totoro#14]
right now if we change the tab from player , we can't go back to the player. It would be great if could continue.
please check this video 

https://user-images.githubusercontent.com/55329452/214921940-bf495708-b313-47b8-9867-741db4e35534.mp4

**Comment by insomniachi** [comment]
Does it not start playing from it left off why you play the same episode again?

I would like to do picture in picture mode for the video player, but that is not supported by the UI framework yet.
let me see what i can do.
