### ISSUE TITLE
crash while downloading

### ISSUE THREAD

**Issue by venkat2305** [insomniachi/Totoro#15]
I tried to download but it crashed immediately.

https://user-images.githubusercontent.com/55329452/214932397-7d98d50d-ef66-49c7-8a51-2865f2c94bc2.mp4

**Comment by insomniachi** [comment]
I was considering removing this download section.
This is actually downloading torrents. would anyone use this instead of downloading the torrents themselves?

**Comment by insomniachi** [comment]
Page removed in favor of torrent streaming.
