### ISSUE TITLE
Crunchyroll issues

### ISSUE THREAD

**Issue by insomniachi** [insomniachi/Totoro#16]
Can I post all the bugs related to crunchyroll here?

Can you try to play " the Angel next door spoils me rotten" and "Vinland saga season 2" in crunchyroll. I think there's an issue with the current season anime. I can't play them but it works fine with completed anime.

Recently aired page is empty for crunchyroll. Can you look into this?

**Comment by insomniachi** [comment]
1. The Angel next door spoils me rotten is fixed
2. Recent episodes now shows, but the api doesn't return which episode aired, so it'll show Episode 0 for now.
3. While looking at Vinland saga i found an issue. for anime with multiple seasons, subbed1 will be season 1 subbed2 will be season 2 and so on. so if you want to play season 2, you'd have to play the same episode number from season 1 and then switch to subbed2, this is a hack, but'll fix it properly later.

**Comment by venkat2305** [comment]
Wow. Thanks for fixing this. You are awesome

**Comment by venkat2305** [comment]
Instead of a recently aired tab, a homepage with a bunch of recommendations would be great. What do you think?

**Comment by insomniachi** [comment]
recommendations would have to come from the providers.
Some providers do have some featured anime. crunchyrolls apis doesn't any recommendations.
If you go to individual anime page, there is recommendations based on that anime.
![image](https://user-images.githubusercontent.com/6525704/215273999-06ab5ca4-e4bb-40ef-ae64-a32f614bba8f.png)
this comes from MAL/Anilist so the selected provider may or may not have these.

**Comment by insomniachi** [comment]
Seasons should work fine now with CR
![image](https://user-images.githubusercontent.com/6525704/215320303-425dc534-935f-490e-9573-885056f9888d.png)

**Comment by venkat2305** [comment]
Can't see season 2 for Tokyo revengers. Can you please check.

**Comment by venkat2305** [comment]
Also The default quality is not being selected as 1080p.

**Comment by venkat2305** [comment]
Can you highlight the selected subtitle and quality?

**Comment by insomniachi** [comment]
1. Api only returns 1 season 
![image](https://user-images.githubusercontent.com/6525704/215335741-02e806a7-150d-4da8-a9ad-536e1838c344.png)
2. Default quality is now auto if it exists, it switches based on your internet speed. it'll take 1080 most of the time. (even if it doesn't start at 1080, it should switch to 1080 eventually if you have the speed.) 
3. For subtitles it would have "(On)" appended. for stream quality probably can do.

**Comment by venkat2305** [comment]
Can you try to play attack on titan season 1.its not playing for me. Maybe because it's not available in the Indian library. Please look into it

**Comment by venkat2305** [comment]
Can you try to play attack on titan season 1.its not playing for me. Maybe because it's not available in the Indian library. Please look into it

**Comment by insomniachi** [comment]
Fixed, there was an episode 0.5 (preview) in attack on titan, which caused a crash when trying to convert to an integer.

**Comment by venkat2305** [comment]
Thanks.
> Api only returns 1 season

1. How can I access Tokyo revengers season 2?
Deom slayer season 2 is totally accessible. 

2. I think having default quality option would be great , since sometimes we seek too forward and then quality suddenly drops. I would wait till it buffers the high quality

3. [Bug] Changing the video quality is resetting the episode progress.

**Comment by venkat2305** [comment]
> I think having default quality option would be great , since sometimes we seek too forward and then quality suddenly drops. I would wait till it buffers the high quality

Because, i have a very high speed connection and sometimes it is blurry. When i switched to 1080p manually there was no issue.

**Comment by insomniachi** [comment]
I'll add a setting on how the default quality is chosen.
It'd be Auto or Highest. and will be Auto by default, you'll have to change it once released.

**Comment by venkat2305** [comment]
1080p quality is not the default for hardsub. Quality is changing when seeking in hardsub
