### ISSUE TITLE
UI issue

### ISSUE THREAD

**Issue by vangbilal** [insomniachi/Totoro#17]
i think there's an issue with the UI , when you try to watch an anime with many episodes like One Piece or Naruto , the list of episodes hide the screen and you can't move or watch , can it be fixed please
![Capture](https://user-images.githubusercontent.com/89322105/215479763-9de7f740-014e-4515-bb0e-948df546ec2e.PNG)

**Comment by vangbilal** [comment]
> ops

can it be fixed ?

**Comment by insomniachi** [comment]
yes

**Comment by insomniachi** [comment]
fixed, added scroll instead of growing in size.

**Comment by vangbilal** [comment]
> fixed, added scroll instead of growing in size.

you're the best bro

**Comment by insomniachi** [comment]
It'll download the installer and tell you when it's ready. then app will restart and install.

**Comment by vangbilal** [comment]
well , when i tried to update from within the app , an error sign appeared so i re-downloaded the installer from the github server

**Comment by insomniachi** [comment]
yeah, you might've closed the application while it was downloading. 
i'll fix it later.
