### ISSUE TITLE
Crashing Issue

### ISSUE THREAD

**Issue by vangbilal** [insomniachi/Totoro#18]
there's a problem in the app , when i select gogo anime provider since it's one of the best english sub/dub providers , the list of animes shows up , but when i choose an anime , it crashs and the app get closed
and there's a problem with the UI , is when you maximize the app while watching an episode the upper bar (minimize , maximize , close) becomes smaller ( the icons are almost gone ) , and thanks for your time

**Comment by insomniachi** [comment]
>there's a problem in the app , when i select gogo anime provider since it's one of the best english sub/dub providers , the list of animes shows up , but when i choose an anime , it crashs and the app get closed

this is fixed

>there's a problem with the UI , is when you maximize the app while watching an episode the upper bar (minimize , maximize , close) becomes smaller ( the icons are almost gone ) , and thanks for your time

this i won't do anything right now, the media player in the UI framework doesn't allow fullscreen yet, i'm hacking it to go fullscreen. this should eventually get fixed when WinUI3 supports it properly.

**Comment by vangbilal** [comment]
okey , glad to hear that
