### ISSUE TITLE
Feature Request - Debrid Service Cached Torrents

### ISSUE THREAD

**Issue by reddit-reaper** [insomniachi/Totoro#19]
Hey guys,

so this app looks pretty awesome and wanted to bring in the idea of adding in debrid services as well. Not sure if you have every used them but if you ever tried most modern kodi addons, syncler, weyd, or stremio+torrentio+kitsu indexer its exactly how that works. you could use cached torrents checked against the premiumize api and links would be immediately avaible at fast speeds. i can go into more detail if needed though. Hit me up here in my email redditreaper86@gmail.com on keybase: redditreapercody

**Comment by insomniachi** [comment]
I've sent you a message on reddit, assuming this is you (reddit_reaper) on reddit.

**Comment by insomniachi** [comment]
added.

**Comment by reddit-reaper** [comment]
Badass I'll test it out. Gj :)
