### ISSUE TITLE
Crash after first auth

### ISSUE THREAD

**Issue by TyShur** [insomniachi/Totoro#2]
The app lauched normaly the first time then after login on MAL the app crashed and keep crashing every lauch after

**Comment by insomniachi** [comment]
can you once again make the app crash and go to Event Viewer (it's an in-built app in windows)
![image](https://user-images.githubusercontent.com/6525704/209157161-31259048-ade0-40f3-9def-eaa3da66ce4b.png)
Windows Logs -> Application -> There would be two errors, can you give me screenshots of both ?

**Comment by TyShur** [comment]
![image](https://user-images.githubusercontent.com/22522015/209414020-90a8c0b8-2f34-41af-a33b-13a74ff2f96b.png)
![image](https://user-images.githubusercontent.com/22522015/209414044-91edc45d-92ba-425b-bd36-f219b2e6969a.png)
![image](https://user-images.githubusercontent.com/22522015/209414105-31d92778-cf85-485d-8e1b-70e4dc58bc2d.png)


i got the third one after relaunch the app a second thime after that 

https://myanimelist.net/profile/ty5hur

u mean in the biography ? other then that don't see

**Comment by insomniachi** [comment]
you have click the error item to see the error, now it's on information.
try deleting C:\Users\<username>\AppData\Local\Totoro\ApplicationData\LocalSettings.json and login with mal again.
and if you don't mind send me the current LocalSettings.json file

**Comment by insomniachi** [comment]
closing no feedback and not reproducing
