### ISSUE TITLE
Ability to watch using an external media player

### ISSUE THREAD

**Issue by Bamboozul** [insomniachi/Totoro#30]
I'd want to watch using my preferred media player, "[MPC-HC](https://github.com/clsid2/mpc-hc)," so that I can change fonts, load subtitles, and so on.

The idea is that if you can add a "Library Folder" option to find the folder where my downloaded anime episodes are saved, and every time I play an episode from this folder, Totoro recognizes it and displays what I'm watching in Discord.

**Comment by insomniachi** [comment]
If external media player is used, totoro cannot know the current position of the anime be played, that it cannot update tracking when you finish watching, or i cannot remember when you stopped watching.
At that point it'll be discord rich presence, and you'll be better of using some discord rich presence for the media player.

![image](https://github.com/insomniachi/Totoro/assets/6525704/034d9ab3-28f6-4654-beca-7ec427bfa66a)
modifying the close caption style here, should also reflect in totoro.

**Comment by Bamboozul** [comment]
> 

This feature is already available in another tracker app named "[Taiga](https://github.com/erengy/taiga)". Maybe you could check it out and bring this feature to Totoro?

**Comment by insomniachi** [comment]
Hmm, seems doable, tried with VLC.
Would you prefer it to do like Taiga, where it detects media player launched,
or would you prefer to show your library within the app, and launch the media player from the app?

**Comment by Bamboozul** [comment]
> Hmm, seems doable, tried with VLC. Would you prefer it to do like Taiga, where it detects media player launched, or would you prefer to show your library within the app, and launch the media player from the app?

I prefer the first choice, "Like Taiga". so that I don't have to open the app every time I want to watch a new episode.

**Comment by insomniachi** [comment]
How does Taiga know when you finish watching episode? It's not updating for me.
Only thing i can do is not prompt user to confirm whether you finished watching the episode when you close the player.

Only on vlc i can reliably know upto which point you've watched.

**Comment by Bamboozul** [comment]
At first, Taiga waits for 10 seconds after playing the episode.

![Screenshot 2023-06-24 145907](https://github.com/insomniachi/Totoro/assets/101983929/01640606-a97a-4de1-9070-81975f715c51)

![Screenshot 2023-06-24 150116](https://github.com/insomniachi/Totoro/assets/101983929/5d3d09fa-955b-4fab-b294-fe6d2fb6751f)

![Screenshot 2023-06-24 150311](https://github.com/insomniachi/Totoro/assets/101983929/c3821e78-c3de-451f-ad38-35d070367187)

And then, when I close MPC, Taiga prompts me to update my anime list.

![Screenshot 2023-06-24 150347](https://github.com/insomniachi/Totoro/assets/101983929/9500e2b7-00c4-4fae-8b3d-d63101a15b63)

**Comment by Bamboozul** [comment]
I see you've published v1.2.0, which includes media detection. Could you also add the "Library Folders" option so Totoro only detects episodes from these folders?

![Screenshot 2023-06-24 194738](https://github.com/insomniachi/Totoro/assets/101983929/0ef5ed8a-281d-411d-9494-229196fd1f91)
