### ISSUE TITLE
Enhancements in video player 

### ISSUE THREAD

**Issue by Aeropro4** [insomniachi/Totoro#31]
**Is your feature request related to a problem? Please describe.**
*The problems 
1) When the player goes to fullscreen, the bottom controller doesn't disappear manually and goes after several seconds in that time it hides the subtitles.
2) can't change the source in the player (well not a very big prob)
3)if i press back then the player continues to play videos .
4) no keyboard shortcuts to forward or backward some seconds (or I don't it)

*Solution 
1) add something like vlc that after a right click the bottom control panel  disappear or decrease the disappearing time
2) its not something a big prob but if u can add an option to change source in player then it would be noice
3) its a bug 
4) there can be 2 things that I don't know the shortcuts or there's none

*alternatives
I can't think of anything

**Additional context**
this softwares real gud but it needs some polishing like when i search for some anime it gives an empty result.

**Comment by Aeropro4** [comment]
K. But I think this point is missed "if I press back then the player continues to play videos ." Cause of numbering mess up

**Comment by insomniachi** [comment]
I've seen that sometimes, but it doesn't happen always, need to how to reproduce it first

**Comment by insomniachi** [comment]
can you list all the shortcuts you want and what they should be?
you won't be able to change shortcuts, adding a control to edit shortcut seems like too much work.

**Comment by Aeropro4** [comment]
> can you list all the shortcuts you want and what they should be?
> you won't be able to change shortcuts, adding a control to edit shortcut seems like too much work.

Umm sorry for the late reply
And for the shortcuts:
- Add keys for forward or backward 10 sec
- Ctrl+ keys for next or previous episode ( if possible else it can be forward/backward 30 sec)
- Space for pause/play
- F key for fullscreen 

I can think of these only for now but these are the most needed ones aswell so
