### ISSUE TITLE
[MPV] media player method, this program allows you to get sharper results while watching a anime.

### ISSUE THREAD

**Issue by yORmOmi** [insomniachi/Totoro#36]
**Is your feature request related to a problem? Please describe.**
Some anime have really bad quality or an insane quality, people want them super high.

**Describe the solution you'd like**

**Describe alternatives you've considered**
[Anime4K](https://github.com/bloc97/Anime4K) + [MVP](https://github.com/bloc97/Anime4K/blob/master/md/GLSL_Instructions_Windows_MPV.md) = good quality

**Additional context**
These programs doesn't require too much usage on Ram or GPU/CPU.

**Their Results**
https://github.com/bloc97/Anime4K#v41-low-resolution-experiment
https://github.com/bloc97/Anime4K#v4

**Comment by insomniachi** [comment]
What is that you want ?
you can use Anime4k + MPV.  totoro should detect and track the anime you're watching #32 

I don't think it's possible to integrate with the inbuilt video player inside app.

**Comment by yORmOmi** [comment]
> What is that you want ? you can use Anime4k + MPV. totoro should detect and track the anime you're watching #32
> 
> I don't think it's possible to integrate with the inbuilt video player inside app.

How do I use it? I downloaded MPV and its not doing anything

**Comment by insomniachi** [comment]
you MPV with totoro?
you'll have to download anime on your own and play it mpv, totoro if open will update mal/anilist
direction streaming with mpv is not yet supported.

**Comment by insomniachi** [comment]
stale
