### ISSUE TITLE
`Schedule` page issue

### ISSUE THREAD

**Issue by bachig26** [insomniachi/Totoro#4]
as you can see in the gif below, the schedule of a anime takes whole screen and i can't see other anime information in it, it's just one anime.

please look into this issue.

### GIF

![Totoro WinUI_bLZgLSPPrF](https://user-images.githubusercontent.com/96393348/209855094-676bab66-c870-4485-b601-a2ca69fa6e59.gif)

**Comment by insomniachi** [comment]
fixed in 0.5.4
