### ISSUE TITLE
A few UI adjustments

### ISSUE THREAD

**Issue by Bamboozul** [insomniachi/Totoro#40]
**User Preferences:**

- An option to choose the default display mode.

**List view:**

- Add more column options such as "season, type, progress with plus and minus to quickly add and remove episodes, score with rating from 0 to 10.
![1](https://github.com/insomniachi/Totoro/assets/101983929/491777bc-514d-4e7b-a960-36891ac1270c)
![2](https://github.com/insomniachi/Totoro/assets/101983929/36ad0882-7e53-475d-91cb-a46f011e420e)
- A new window containing anime information will open when you double-click the anime title.
![3](https://github.com/insomniachi/Totoro/assets/101983929/9e0843a8-0daa-48fa-9ec9-32a5c59d720c)
- When you click on the anime title, the anime poster appears in the bottom left.
![4](https://github.com/insomniachi/Totoro/assets/101983929/a9398c2a-fa38-4a16-8326-e980c36e61e2)

**Comment by Bamboozul** [comment]
Navigating between tabs or closing the app will reset the column order to the default.

![30](https://github.com/insomniachi/Totoro/assets/101983929/881016af-cf9f-46b8-bde2-bebcb32faea8)

**Comment by Bamboozul** [comment]
Also, would it be possible to have a "Countdown" or "Next Episode in" option?

**Comment by insomniachi** [comment]
> Also, would it be possible to have a "Countdown" or "Next Episode in" option?

Yes

![image](https://github.com/insomniachi/Totoro/assets/6525704/bcef503b-cc8b-4851-be7f-98f71c9a68e7)

**Comment by Bamboozul** [comment]
> > Also, would it be possible to have a "Countdown" or "Next Episode in" option?
> 
> Yes
> 
> ![image](https://user-images.githubusercontent.com/6525704/255686425-bcef503b-cc8b-4851-be7f-98f71c9a68e7.png)

Additionally, allow us to rate the anime by clicking the (-) in the score column.

![Screenshot 2023-07-24 205730](https://github.com/insomniachi/Totoro/assets/101983929/a0574170-6ffa-4ba3-a68f-f55def4d51c6)

**Comment by Bamboozul** [comment]
> > Also, would it be possible to have a "Countdown" or "Next Episode in" option?
> 
> Yes
> 
> ![image](https://user-images.githubusercontent.com/6525704/255686425-bcef503b-cc8b-4851-be7f-98f71c9a68e7.png)

Sorting by "Next Episode" is not working as intended, and as the gif shows, it's sorting by "Title".

![30](https://github.com/insomniachi/Totoro/assets/101983929/ccfb0445-c306-44f7-9470-5d67a903fb52)

**Comment by insomniachi** [comment]
i have not implemented sort for all columns.
there is a function called GetSortComparer in Totoro.Core/ViewModels/UserListViewModel.cs
![image](https://github.com/insomniachi/Totoro/assets/6525704/526d2c70-f848-4857-8732-d77140b5ad97)
you can add 2 lines to make it work.

Column name is value of Tag property in Totoro.WinUI/Views/UserListPage.xaml
![image](https://github.com/insomniachi/Totoro/assets/6525704/6c34ee56-aac3-4822-bac1-6d02b7433af5)

if you make a I'll merge

**Comment by Bamboozul** [comment]
**List view:**
- Click again to hide the poster and synopsis.
- Click the anime poster to open the anime page on MyAnimeList or Anilist in your browser.

![List view](https://github.com/insomniachi/Totoro/assets/101983929/06779f75-fb79-4a8d-a767-26740c5cb7df)


**Grid view:**
- Click the anime poster to open the anime page on MyAnimeList or Anilist in your browser.

![Grid view](https://github.com/insomniachi/Totoro/assets/101983929/2a3d9846-6289-407d-b21a-acc85cea2ee6)

**Comment by Bamboozul** [comment]
App crashes if you open the anime info page and quickly click the anime poster before it loads.

![30](https://github.com/insomniachi/Totoro/assets/101983929/13d04d1d-716e-4533-aa7d-292d838a521a)

Log:
```
2023-08-02 19:50:24.903 +02:00 [DBG] Current Version, 2.0.0.0
2023-08-02 19:50:24.919 +02:00 [DBG] Latest Version, 1.2.4
2023-08-02 19:50:25.011 +02:00 [INF] Loaded plugin AllAnime
2023-08-02 19:50:25.012 +02:00 [INF] Loaded plugin Anime Pahe
2023-08-02 19:50:25.013 +02:00 [INF] Loaded plugin Gogo Anime
2023-08-02 19:50:25.013 +02:00 [INF] Loaded plugin Marin
2023-08-02 19:50:25.015 +02:00 [INF] Loaded plugin Yugen Anime
2023-08-02 19:50:25.015 +02:00 [INF] Loaded plugin Zoro
2023-08-02 19:50:25.020 +02:00 [INF] Loaded plugin Anime Tosho
2023-08-02 19:50:25.027 +02:00 [INF] Loaded plugin Nya
2023-08-02 19:50:25.029 +02:00 [INF] Loaded plugin MPV
2023-08-02 19:50:25.030 +02:00 [INF] Loaded plugin MPC-HC
2023-08-02 19:50:25.031 +02:00 [INF] Loaded plugin VLC Media Player
2023-08-02 19:50:25.032 +02:00 [INF] Loaded plugin Windows Media Player
2023-08-02 19:50:25.294 +02:00 [DBG] Navigated to UserListViewModel
2023-08-02 19:50:48.211 +02:00 [DBG] Navigated to AboutAnimeViewModel
2023-08-02 19:50:57.221 +02:00 [DBG] Navigated to UserListViewModel
2023-08-02 19:51:05.925 +02:00 [DBG] Navigated to AboutAnimeViewModel
2023-08-02 19:51:06.396 +02:00 [FTL] Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Totoro.WinUI.Views.AboutAnimePage.ImageTapped(Object sender, TappedRoutedEventArgs e) in D:\Stuff\Downloads\Compressed\Totoro-main-8904660\Totoro.WinUI\Views\AboutAnimePage.xaml.cs:line 39
   at WinRT._EventSource_global__Microsoft_UI_Xaml_Input_TappedEventHandler.EventState.<GetEventInvoke>b__1_0(Object sender, TappedRoutedEventArgs e)
   at ABI.Microsoft.UI.Xaml.Input.TappedEventHandler.Do_Abi_Invoke(IntPtr thisPtr, IntPtr sender, IntPtr e)
```

**Comment by Bamboozul** [comment]
When you change the display mode from My List and switch tabs, the app reverts to the default list display mode.

**expected behavior:**

Only revert to the default display mode when you close and reopen the app.

![30](https://github.com/insomniachi/Totoro/assets/101983929/8a22eaa2-62c5-47da-9710-0bba800f3a74)

![Grid-view](https://i.ibb.co/k5QJnPw/Grid-view.gif)

![List-view](https://i.ibb.co/nmjtchV/List-view.gif)

**Comment by Bamboozul** [comment]
When you change the display mode from My List and switch tabs, the app reverts to the default list display mode.

**expected behavior:**

Only revert to the default display mode when you close and reopen the app.

![30](https://github.com/insomniachi/Totoro/assets/101983929/8a22eaa2-62c5-47da-9710-0bba800f3a74)

[Grid view](https://i.ibb.co/k5QJnPw/Grid-view.gif)

[List view](https://i.ibb.co/nmjtchV/List-view.gif)

**Comment by Bamboozul** [comment]
Plan to Watch, On-Hold, Completed, and Dropped are showing the "Next Episode" for Watching rather than their own.

![30](https://github.com/insomniachi/Totoro/assets/101983929/9d28f35c-8ef6-4a77-bd05-8063af7be712)

**Comment by Bamboozul** [comment]
Also, the app is now known as "ToolTip" in the system tray.

![Screenshot 2023-08-04 214815](https://github.com/insomniachi/Totoro/assets/101983929/6cd5823a-901c-4de5-bd0c-af08da9f8ac9)

v1.2.5.0

**Comment by Bamboozul** [comment]
**Grid view:**
- a "Number of Items per Row" option that allows you to choose the number of items per row in the grid view.
- an option to add the next episode time for my list tab as well.
![Screenshot 2023-08-05 162755](https://github.com/insomniachi/Totoro/assets/101983929/93e6bb4d-4536-40ba-8a2d-ffceefb3757b)

**Comment by Bamboozul** [comment]
**Grid view:**
Yellow: It would be better to put the next episode's time at the top of the poster.
Red: Change the next episode time from 3 days, 3 hours to EP5: 3d 03h 45m and reduce the text size.
Green: Add the average score.
Blue: Add the user score.
Black: Add episode progresses.
White: Add two buttons (plus and minus) to add and remove episodes.

![Screenshot 2023-08-06 121651](https://github.com/insomniachi/Totoro/assets/101983929/daf4b124-7015-4fcd-9f1c-e7b46039f77f)

**Comment by Bamboozul** [comment]
**Grid view:**
- Reduce the average score size.

**Before:**

![Screenshot 2023-08-08 221036](https://github.com/insomniachi/Totoro/assets/101983929/ede966a4-9464-46e1-8ab2-7921f70795ea)

**After:**

![Screenshot 2023-08-08 221019](https://github.com/insomniachi/Totoro/assets/101983929/44f6c46f-a53e-4aee-9b53-cafe3eee8ae3)

- Remove the context menu button and make it accessible when right-clicking the anime card.

![totoro card-x](https://github.com/insomniachi/Totoro/assets/101983929/e0a983ec-aaf6-4595-8622-a8e06e22437e)

- Remove (if possible) or reduce the size of the square around the increment and decrement buttons to make room for other items.
- Add an option to show or hide the average score.
- Again, an option to place the time bar for the next episode at the top of the anime card or the top of the poster.

**at the top of the anime card:**

![livechart](https://github.com/insomniachi/Totoro/assets/101983929/826a507f-d91c-473c-8974-d70327b390e7)

**at the top of the poster:**

![totoro card](https://github.com/insomniachi/Totoro/assets/101983929/092416e4-e0df-4ea1-81d3-61901f8297de)


**Issues:**

- Posters are a little hazy and unclear.

![Screenshot 2023-08-08 220603](https://github.com/insomniachi/Totoro/assets/101983929/93574809-45e1-429e-a541-08985dfbc9fc)

- No room for user score when using a small anime card.

**Actual:**

![totoro card-rating](https://github.com/insomniachi/Totoro/assets/101983929/d287f0de-bb6a-44a7-980b-a3c762df2e03)

**Expected to be similar to this:**

![Screenshot 2023-08-08 231937](https://github.com/insomniachi/Totoro/assets/101983929/dc09f959-f428-472a-844d-aa0f6e061584)

**Comment by Bamboozul** [comment]
**Grid view:**
- Add sort by option.

![Screenshot 2023-08-08 233106](https://github.com/insomniachi/Totoro/assets/101983929/3ab0d1d2-b3a7-4953-99bd-ae0af70540b1)

**Comment by insomniachi** [comment]
Sort is loading what i set previously for me, (tested in grid view)

**Comment by Bamboozul** [comment]
> Sort is loading what i set previously for me, (tested in grid view)

Same for me, just in the wrong order.

This is when I launch the app (this order for "Data Completed, Ascending"):

![Screenshot 2023-08-10 182639](https://github.com/insomniachi/Totoro/assets/101983929/5db5d5e0-1a4b-4369-882a-3d5aeaeaaeaa)


And this is how it should look:

![Screenshot 2023-08-10 182533](https://github.com/insomniachi/Totoro/assets/101983929/45f9d211-97c0-427b-ae8f-95add4f74582)

**Comment by Bamboozul** [comment]
> Sort is loading what i set previously for me, (tested in grid view)

I think the problem is with "Next Episode"
[gif.zip](https://github.com/insomniachi/Totoro/files/12315312/gif.zip)
