### ISSUE TITLE
Discord rich presence

### ISSUE THREAD

**Issue by Bamboozul** [insomniachi/Totoro#42]
- Discord's rich presence should only be activated when you start watching and not when the app is being used.

![Screenshot 2023-07-23 172441](https://github.com/insomniachi/Totoro/assets/101983929/ae0272c2-6427-4bc1-875c-1dc737d43fc1)

- Add an option to choose whether to display or hide the remaining time left.

![Screenshot 2023-07-23 172422](https://github.com/insomniachi/Totoro/assets/101983929/1a4b3215-c441-4694-9af0-0e812a345fda)

- Add a "View Anime" button to display the anime page on MyAnimeList or Anilist.

![Screenshot 2023-07-23 194448](https://github.com/insomniachi/Totoro/assets/101983929/95c0a9b6-29ae-45d8-ba73-8c1c94793c94)

**Comment by insomniachi** [comment]
would you like to help with 2 and 3 ?

**Comment by Bamboozul** [comment]
> would you like to help with 2 and 3 ?

I'd like to help, but I don't have much knowledge about coding.

Also, Taiga already has these options, so this should help right?

**Comment by insomniachi** [comment]
I know how to implement it.
This is a small change, so new contributors could easily add it. that's why I asked.
But since you're new to coding, then it might not be trivial.
