### ISSUE TITLE
Nothing in discover section

### ISSUE THREAD

**Issue by Aeropro4** [insomniachi/Totoro#43]
When clicking on discover section only the recently aired and search text and search bar is coming except that nothing is there, when searching an anime name it just loads for a few milliseconds and dissapears 

**Expected behavior**
Some anime should've come

![Totoro WinUI_fXwIhc5hN6](https://github.com/insomniachi/Totoro/assets/113044496/a3eeb5fd-fd38-4b13-9dd4-c78a3b41f00d)
![Totoro WinUI_i6N4wLg5kh](https://github.com/insomniachi/Totoro/assets/113044496/e8204f74-3e57-4973-b57b-24f2d4e41d5f)
![Totoro WinUI_1enUY8qvUb](https://github.com/insomniachi/Totoro/assets/113044496/9d292100-d678-4a22-ab59-b320f1864587)

**Comment by insomniachi** [comment]
what provider are you using?
1. Check your internet.
2. Maybe the provider is broken, use another one
