### ISSUE TITLE
Unwatched episode notification badge

### ISSUE THREAD

**Issue by Bamboozul** [insomniachi/Totoro#48]
I've already watched all the aired episodes of [Mushoku Tensei II: Isekai Ittara Honki Dasu](https://myanimelist.net/anime/51179/Mushoku_Tensei_II__Isekai_Ittara_Honki_Dasu), including the [special](https://myanimelist.net/anime/55818/Mushoku_Tensei_II__Isekai_Ittara_Honki_Dasu_-_Shugo_Jutsushi_Fitz) (4+1), yet I still have the notification badge that says I have one unwatched episode.

![List view](https://github.com/insomniachi/Totoro/assets/101983929/cc868e23-4c7e-4783-bba0-2631e199f8a2)

![Grid view](https://github.com/insomniachi/Totoro/assets/101983929/a52ebc16-392c-428c-82d3-5b97cd22fb9f)

**Comment by insomniachi** [comment]
I'm using anilist api to get the next airing episode, subtracting 1 will give aired episode,
i'm taking the difference of this and watched episodes in tracking to show in the badge.

anilist is saying 5 episodes have aired [here](https://[anilist.co/graphiql](https://anilist.co/graphiql?query=%7B%0A%20%20Media(id%3A%20146065)%0A%20%20%7B%0A%20%20%20%20title%0A%20%20%20%20%7B%0A%20%20%20%20%20%20english%0A%20%20%20%20%7D%2C%0A%20%20%20%20nextAiringEpisode%0A%20%20%20%20%7B%0A%20%20%20%20%20%20episode%2C%0A%20%20%20%20%20%20timeUntilAiring%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A)?query=%7B%0A%20%20Media(id%3A%20146065)%0A%20%20%7B%0A%20%20%20%20title%0A%20%20%20%20%7B%0A%20%20%20%20%20%20english%0A%20%20%20%20%7D%2C%0A%20%20%20%20nextAiringEpisode%0A%20%20%20%20%7B%0A%20%20%20%20%20%20episode%2C%0A%20%20%20%20%20%20timeUntilAiring%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A)

probably it's counting the special episode, there is nothing i can do in this case,

**Comment by Bamboozul** [comment]
> I'm using anilist api to get the next airing episode, subtracting 1 will give aired episode, 

Is it feasible to include an option to select which API to use? (If that is not too much work for you).

**Comment by insomniachi** [comment]
MAL api doesn't give anything about airing schedule, or number of episodes aired.
which other api are you talking about

**Comment by Bamboozul** [comment]
> MAL api doesn't give anything about airing schedule, or number of episodes aired. which other api are you talking about

[Jikan - Unofficial MyAnimeList.net PHP API](https://jikan.moe/)

**Comment by insomniachi** [comment]
mal's episode tab doesn't always update
![image](https://github.com/insomniachi/Totoro/assets/6525704/44140eb2-a356-4fa3-b2c2-cb21c28b8919)
![image](https://github.com/insomniachi/Totoro/assets/6525704/ebe1b414-d0af-4c1e-a55b-0cddc94527d6)
episode 5 was released 17 hours ago.
jikan just scrapes MAL.
i don't see value in using it, Anilist api would be more accurate 90% of the time.

**Comment by Bamboozul** [comment]
> mal's episode tab doesn't always update ![image](https://user-images.githubusercontent.com/6525704/258583059-44140eb2-a356-4fa3-b2c2-cb21c28b8919.png) ![image](https://user-images.githubusercontent.com/6525704/258583068-ebe1b414-d0af-4c1e-a55b-0cddc94527d6.png) episode 5 was released 17 hours ago. jikan just scrapes MAL. i don't see value in using it, Anilist api would be more accurate 90% of the time.

We stick with Anilist API then.
