### ISSUE TITLE
Window size and position

### ISSUE THREAD

**Issue by Bamboozul** [insomniachi/Totoro#51]
Would it be possible to add these two options?
- Remember window size.
- Remember window position.

![Screenshot 2023-08-19 153754](https://github.com/insomniachi/Totoro/assets/101983929/7c2b0592-4c46-426e-a78c-1bdde41947de)

**Comment by insomniachi** [comment]
would it hurt to always save, not give the option ?

**Comment by Bamboozul** [comment]
> would it hurt to always save, not give the option ?

It's a matter of preference. Some may prefer that it is always saved,  while others may not. So in my opinion, an option would be better.
