### ISSUE TITLE
Italian Default Stream Provider

### ISSUE THREAD

**Issue by Marioeluigi24** [insomniachi/Totoro#53]
**Is your feature request related to a problem? Please describe.**
Technically it's not a problem but it would be awesome if you could add an Italian Stream Provider

**Describe the solution you'd like**
Under the Default Stream Provider section you can add the option to search and view the anime content on Animesaturn domain

**Describe alternatives you've considered**
-

**Additional context**
The URL that contain all their official domain is this "https://www.animesaturn.me/" as they sometimes take down a certain domain (basically this is a list with all their domains).
Now the most relevant and used is "https://www.animesaturn.tv/".

Thank you in advance!

**Comment by insomniachi** [comment]
added

**Comment by Marioeluigi24** [comment]
> added

thank you <3
