### ISSUE TITLE
[Arabic] WitAnime Stream Provider

### ISSUE THREAD

**Issue by Bamboozul** [insomniachi/Totoro#54]
Main domain: [Main](https://witanime.com)
Recently aired: [Link](https://witanime.ink/episode/)

**Comment by insomniachi** [comment]
can you check by running from source in debug mode ?
this and Anime4up looks like the same site, so i won't add that one unless there is a good reason.

**Comment by Bamboozul** [comment]
> can you check by running from source in debug mode ? this and Anime4up looks like the same site, so i won't add that one unless there is a good reason.

All plugins are loading the episodes for me except for AnimeSaturn and WitAnime.

![Screenshot 2023-08-31 184934](https://github.com/insomniachi/Totoro/assets/101983929/8cbbb174-5c59-4421-98eb-3e16372546f3)

**Comment by insomniachi** [comment]
not implemented for those two yet.

**Comment by Bamboozul** [comment]
Also, I noticed a few issues with some of the plugins.
- Yugen Anime
![Screenshot 2023-08-31 191531](https://github.com/insomniachi/Totoro/assets/101983929/bcc61545-78e4-4a0c-8612-205939cc6e82)

![Yugen Anime](https://github.com/insomniachi/Totoro/assets/101983929/b7a7d841-3bdf-4089-9c67-9d3c4fda50d4)

Gogo Anime
![Gogo Anime](https://github.com/insomniachi/Totoro/assets/101983929/29a9a0dc-e429-420c-96d5-1348312971f3)

Marin
![Marin](https://github.com/insomniachi/Totoro/assets/101983929/4ad4d089-4843-4a39-8f5c-04a76f1a5756)

![Screenshot 2023-08-31 191847](https://github.com/insomniachi/Totoro/assets/101983929/42b64f99-12b0-4c13-8fb9-420371704aec)

**Comment by insomniachi** [comment]
gogoanime you might need to change url in settings.

**Comment by insomniachi** [comment]
marin, there seems to be some ddos protection, download link is in log file, that works if you put it in browser.

**Comment by Bamboozul** [comment]
I'm getting these errors when I'm trying to watch Jujutsu Kaisen S2 EP5

![Screenshot 2023-09-01 141431](https://github.com/insomniachi/Totoro/assets/101983929/38ce6d1f-38d6-445d-a48d-ee3df1e3ca39)

![Screenshot 2023-09-01 141647](https://github.com/insomniachi/Totoro/assets/101983929/797ee932-44d0-4a60-a40f-953630f8d46c)

Also, some anime show the previous episode or the one before it rather than the recently aired one.

![Screenshot 2023-09-01 141358](https://github.com/insomniachi/Totoro/assets/101983929/1350b3e2-a688-482a-b5bf-35351f0a542c)

**Comment by insomniachi** [comment]
New episodes from google drive gives this error, because of rate limiting (too many people accessing the file),
only 4shared, and soraplay are working now, and google drive for older episodes.
rest are not giving any response.

**Comment by Bamboozul** [comment]
The latest version, 1.3.0, does not include WitAnime.

![Screenshot 2023-09-13 125656](https://github.com/insomniachi/Totoro/assets/101983929/680e6ffd-d3ea-496b-8e73-dbc6860ca19a)

**Comment by insomniachi** [comment]
should be available now without app update
