### ISSUE TITLE
[Arabic] Anime4up Stream Provider

### ISSUE THREAD

**Issue by Bamboozul** [insomniachi/Totoro#55]
Main domain: [Main](https://anime4up.tv)
Recently aired: [Link](https://anime4up.cam/episode/)

**Comment by insomniachi** [comment]
I'm not exactly good at web scraping, most of my scrapers are ported from other similar projects.
both the sites you mentioned, I don't think I can scrape.
If some other projects are scraping it, I can take a look.

**Comment by Bamboozul** [comment]
> I'm not exactly good at web scraping, most of my scrapers are ported from other similar projects. both the sites you mentioned, I don't think I can scrape. If some other projects are scraping it, I can take a look.

I found this [plugin](https://codeberg.org/cloudstream/arab/src/branch/main/Anime4upPack/src/main/kotlin/com/anime4up) for both sites. but I'm not sure if it'll help you.

**Comment by Bamboozul** [comment]
For [WitAnime](https://github.com/3v1ltw1n0x01/anime_scraper)

**Comment by Bamboozul** [comment]
Aniyomi extensions for both [Here](https://github.com/aniyomiorg/aniyomi-extensions/tree/master/src/ar/anime4up) and [Here](https://github.com/aniyomiorg/aniyomi-extensions/tree/master/src/ar/witanime).
