### ISSUE TITLE
Player menu issue

### ISSUE THREAD

**Issue by Aeropro4** [insomniachi/Totoro#60]
Pls do something about the player menu which blocked the subtitles first few seconds

**Comment by Aeropro4** [comment]
> Pls do something about the player menu which blocks the subtitles first few seconds

**Comment by Aeropro4** [comment]
Sorry for late reply and thx for your efforts but sorry to say its not that useful as i move my mouse then it again hides the subs. 
But I have a solution that i saw from vlc and that's to make the player menu opaque, so is it possible to do that or not?

**Comment by insomniachi** [comment]
controls are transparent now
