### ISSUE TITLE
Feature Request: Integrate SIMKL into Totoro

### ISSUE THREAD

**Issue by Azmarine13** [insomniachi/Totoro#65]
Please integrate SIMKL into Totoro. 

- **Anime Page:** https://simkl.com/anime/ 
- **API Documentation:** https://api.simkl.com/

**Comment by insomniachi** [comment]
Are you okay with just tracking ?
the api doesn't seem to have all the metadata i need

**Comment by insomniachi** [comment]
for some shows in your list simkl return same name for All seasons
![image](https://github.com/insomniachi/Totoro/assets/6525704/86d15358-f766-4086-8eed-5f63b9117342)
so provider will aways find season 1 when streaming.

I have added a context menu action to add an alternate name, that will be used when searching providers.
![image](https://github.com/insomniachi/Totoro/assets/6525704/da3cc206-01be-4a35-b008-f46a97a16bc7)

Initial level support available in latest release
