### ISSUE TITLE
Real-Debrid

### ISSUE THREAD

**Issue by nimmy404** [insomniachi/Totoro#68]
Any plans to add real-debrid support, since its more popular and has a lot more cached content.
Thanks

**Comment by insomniachi** [comment]
I can add, but you'll have to share your API token for me to develop. you can reset the token after I'm done.

**Comment by nimmy404** [comment]
> I can add, but you'll have to share your API token for me to develop. you can reset the token after I'm done.

Sure, add you on discord?

**Comment by insomniachi** [comment]
user id is 259948200092237825
username is Insomniachi

**Comment by insomniachi** [comment]
Added
![image](https://github.com/insomniachi/Totoro/assets/6525704/661bb967-215b-433b-9fe4-24f57fa06ce8)
Update API key here

In torrenting screen click play
![image](https://github.com/insomniachi/Totoro/assets/6525704/41d1df44-af75-4d55-bdfc-64cd562b2531)

might crash if it's not cached already, (didn't see any api to check for availability of multiple torrents in single request)
