### ISSUE TITLE
Please add Video Playback Speed! x1.25 x1.5....etc

### ISSUE THREAD

**Issue by xHyperVoid** [insomniachi/Totoro#69]
Been using this since i found about it recently the only thing that makes me not use it is the incapability of having a video playback speed to increase or decrease the stream! Will really appreciate if this can be implemented!

**Comment by insomniachi** [comment]
added
![image](https://github.com/insomniachi/Totoro/assets/6525704/3e905633-2cd6-491f-a218-b1c0b66ee9cc)
