### ISSUE TITLE
improve back button 'especially for settings'

### ISSUE THREAD

**Issue by bachig26** [insomniachi/Totoro#73]
**Describe the bug**

the back button isn't working properly and greyed out. and currently it's difficult to navigate out of the different menu structures like grid view or others.

**Expected behavior**

1. add the functionality to use the keyboard key like 'Backspace' to navigate out of the menus.

2. please have a look at the current backspace button and i would like to see if it's possible to have the back button to be more flexible to use at every menus possible.

**Desktop (please complete the following information):**
 - Version: 1.4.6

**Comment by insomniachi** [comment]
Alt + Left can be used as back.
Settings can be fixed.

i don't understand this
`and currently it's difficult to navigate out of the different menu structures like grid view or others.`

**Comment by insomniachi** [comment]
add few more shortcuts
Alt + D => Discover  Anime,
Alt + L => My List
Alt + S => Seasonal
Alt + T => Torrenting
Ctrl + Alt + S => Settings
