### ISSUE TITLE
Error authenticating MAL

### ISSUE THREAD

**Issue by blindmodz** [insomniachi/Totoro#78]
**Describe the bug**
Trying to log in using Facebook get this error.

**To Reproduce**
1. Try to connect MyAnimeList account
2. Select sign in with Facebook

**Expected behavior**
Log in using Facebook.

**Screenshots**
![image](https://github.com/insomniachi/Totoro/assets/22939330/10f9c505-3875-4f59-bd1a-119e7c01ff31)

**Desktop (please complete the following information):**
 - Version 1.5.1.0

**Comment by insomniachi** [comment]
check if it fixed for you, i couldn't really test, don't want to create a new mal account with fb

**Comment by blindmodz** [comment]
Yep, now I was able to log in using Facebook.
