### ISSUE TITLE
can't scroll up to login with  MAL

### ISSUE THREAD

**Issue by 021ash** [insomniachi/Totoro#84]
**Describe the bug**

**To Reproduce**
1. Go to 'settings>tracking'
2. Click on 'connect'
3. Scroll down to 'couldn't'

**Expected behavior**
show login button 

**Screenshots**

![Screenshot (1)](https://github.com/insomniachi/Totoro/assets/108949366/6d48827e-605b-4fc8-9b2d-f7e69b90be3b)

**Desktop (please complete the following information):**
 - Version [even before 1.5.6]

**Additional context**
login option couldn't been seen but was there for anilist problably because of longer page for MAL

**Comment by insomniachi** [comment]
what is your display resolution?

**Comment by 021ash** [comment]
1366 × 768
Its okay  if not possible just making sure it's not a bug

**Comment by insomniachi** [comment]
It's possible, I just need to reduce the height of the dialog.

**Comment by 021ash** [comment]
Ok, thanks.
