### ISSUE TITLE
App crashing 

### ISSUE THREAD

**Issue by Ash69123** [insomniachi/Totoro#86]
**Describe the bug**
The app just crashes when you open it. It dosent even show the UI I checked task manager and the app pops up for 3 seconds then vanishes. If you open it by double clicking shortcut nothing happens 

**To Reproduce**
1. Just open the app 

**Expected behavior**
The app is supposed to open and display the UI.

**Screenshots**
None available as it crashes.

**Desktop (please complete the following information):**
 - Version 1.5.8

**Additional context**
No

**Comment by insomniachi** [comment]
Has the app ever worked for you? is this your first time installing?

**Comment by Ash69123** [comment]
the app had worked for me but it was a hit or miss sometimes it refused to start after few tries it would start 
now even that dosent work and no this isint my first install

**Comment by insomniachi** [comment]
Uninstall installed version.
delete contents of C:\Users\<username>\AppData\Local\Totoro
do a fresh install.
and sends logs if it crashes.

**Comment by Ash69123** [comment]
Aah thank you its working now
