### ISSUE TITLE
Auto selecting previous source

### ISSUE THREAD

**Issue by Ash69123** [insomniachi/Totoro#88]
**Is your feature request related to a problem? Please describe.**
Its very annoying having to choose different source for only a specific anime every time 

**Describe the solution you'd like**
I would like a feature be implemented which always auto selects the last source used on that anime every time 

**Describe alternatives you've considered**
No

**Additional context**
![image](https://github.com/insomniachi/Totoro/assets/127380679/36d97c24-fd62-4db6-8ffe-e884fd1aabda)
![image](https://github.com/insomniachi/Totoro/assets/127380679/6bd20a8a-6fca-4d16-b5ac-849c9a33d16d)
for allanime it would be good if the sub/dub menu is also auto selected to the previous state

**Comment by insomniachi** [comment]
I won't make it remember the last selection. instead i'll allow you to set provider for each anime.
![image](https://github.com/insomniachi/Totoro/assets/6525704/6d8404a7-5cab-46df-9752-7e53028c0b85)
![image](https://github.com/insomniachi/Totoro/assets/6525704/c2a4e4ce-0d41-435a-ae42-471c69c58da9)

**Comment by Ash69123** [comment]
ohh thanks
