### ISSUE TITLE
Make changes persistent

### ISSUE THREAD

**Issue by bachig26** [insomniachi/Totoro#9]
[1] The settings changes is not persistent for next/future sessions.

Please have the settings to be persistent.

[2] Also another request is to make the window size and position to be remembered or persistent as the last session.

**Comment by insomniachi** [comment]
which settings are not saving ?

**Comment by bachig26** [comment]
> which settings are not saving ?

Every one of it, maybe it's due to update/installation of new version makes it override the previous settings.

**Comment by insomniachi** [comment]
that is strange, it should save.
can you send me the log file?
AppData\Local\Totoro\ApplicationData\Logs

**Comment by bachig26** [comment]
> that is strange, it should save. can you send me the log file? AppData\Local\Totoro\ApplicationData\Logs

[log20221229.txt](https://github.com/insomniachi/Totoro/files/10325386/log20221229.txt)
[log20221230.txt](https://github.com/insomniachi/Totoro/files/10325387/log20221230.txt)

**Comment by insomniachi** [comment]
this log files don't have anything related to you changing settings. looks like you are in the media player page.
delete today log file, open app, go to settings, change some values and give log.
