### ISSUE TITLE
A clearer, non-blurry image of the poster

### ISSUE THREAD

**Issue by Bamboozul** [insomniachi/Totoro#96]
Can the app provide a higher quality image of the poster, comparable to the one on the MyAnimeList website?

a few samples to compare (1=MAL,2=Totoro):-

![Kono Subarashii Sekai ni Shukufuku wo! 3](https://github.com/insomniachi/Totoro/assets/101983929/0d6211ea-b7b2-405f-8ce0-ce02f447632f)
![Tensei shitara Slime Datta Ken 3rd Season](https://github.com/insomniachi/Totoro/assets/101983929/908572d9-fd94-4277-9c42-ae3d51d6b513)
![Tsuki ga Michibiku Isekai Douchuu 2nd Season](https://github.com/insomniachi/Totoro/assets/101983929/baab0709-e3ca-4ec3-9569-f003d048a933)

**Comment by insomniachi** [comment]
Iam using the highest quality picture picture, this is probably due the stretching of the image to fit card size.
Mal Large poster is 423 * 600

the image would look better if the card size were around the same size, or I could disable stretching then it cannot show the full image

![image](https://github.com/insomniachi/Totoro/assets/6525704/70aaa773-5e0d-48f4-ae27-3334c87fd61c)

**Comment by Bamboozul** [comment]
Wouldn't it be better to just leave an option for how many items per row, let's say from 3 to 6, and have the card size auto-edit to display the full size of the medium image without stretching?

![2](https://github.com/insomniachi/Totoro/assets/101983929/55beaaee-6d67-417d-9f54-28a076ed0c47)
![3](https://github.com/insomniachi/Totoro/assets/101983929/692bea36-fa37-4b5a-a52d-53e926ee5bfd)
![4](https://github.com/insomniachi/Totoro/assets/101983929/2aa59355-ed7e-4a87-8594-6a5a81494045)
![5](https://github.com/insomniachi/Totoro/assets/101983929/076e7101-6f54-4f9a-bf13-2b25bc9f55fe)

**Comment by insomniachi** [comment]
it is already doing that, in settings you are setting the minimum size. if number of items is not enough to fill a row, it will use this size,
![image](https://github.com/insomniachi/Totoro/assets/6525704/c5f8a89f-d451-49b7-9231-39f83f982764)

**Comment by Bamboozul** [comment]
> if you set 4 as column size but you have enough space to display 4.5 cards, then it'll distribute the 0.5 card with equally across all the four

What I mean is that we shouldn't make the card so big that we are forced to stretch the image.
In this scenario, I believe it would be better not to include the remaining 0.5 at all.

**Comment by Bamboozul** [comment]
In my opinion, it would be better to lock and adjust the maximum card size to display the full medium image and, if there is a space, leave it as it is.

**Comment by insomniachi** [comment]
i'll be exposing these as settings to let the user decide on what he wants.
currently these settings exist on the settings page, i'll be moving it to the user list page to know the effect in real time
![image](https://github.com/insomniachi/Totoro/assets/6525704/2fc9cce2-ba86-4ec7-a7e8-8f04697123b5)

**Comment by Bamboozul** [comment]
1- The countdown to the next episode does not exist.
2- Add the ability to left-click the poster on the info page, which will redirect you to the anime MAL page.
3- When you close and reopen the app, it doesn't remember the exact size of the window.

**Comment by insomniachi** [comment]
1) count downs should be there, maybe something went wrong the anilist api
3) windowing is not consistent in the ui framework, nothing i can do.

**Comment by Bamboozul** [comment]
> 1. count downs should be there, maybe something went wrong the anilist api
Yes, the issue could be on the Anilist side. Anyway, it's back, and there's no problem.

**Comment by Bamboozul** [comment]
> 1. count downs should be there, maybe something went wrong the anilist api

Yes, the issue could be on the Anilist side. Anyway, it's back, and there's no problem.
